<?php

/**
 * @file
 * B5 Furdle theme file.
 */
/**
 * Implements hook_preprocess_html().
 */
function b5_furdle_preprocess_html(&$vars) {
  // Get the current path
  $current_path = \Drupal::service('path.current')->getPath();
  $internal = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Assign it to body class 
  $vars['attributes']['class'][] = str_replace("/", "", $internal);
}